server:
  port: 7103
spring:
  application:
    name: web
    
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://wind.qdfae.com:7000/eureka/
      healthcheck: 
        enabled: true   
#actuator 监控配置
management:
  port: 8103
  context-path: /admin
  
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false 

  